name: Run healthcheck

on:
  schedule:
  # Once per week
  - cron: "0 0 * * 0"

jobs:
  healthcheck:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Healthcheck
      env:
        SRT_PASSWORD: ${{ secrets.SRT_PASSWORD }}
        SRT_USERNAME: ${{ secrets.SRT_USERNAME }}
      run: |
        pip install pytest
        pytest SRT -x
