name: Run standard checks on push/pull request

on:
  push:
      branches:
      - master
  pull_request_target:
      types: [labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SRT_PASSWORD: ${{ secrets.SRT_PASSWORD }}
          SRT_USERNAME: ${{ secrets.SRT_USERNAME }}
        run: |
          pip install pytest
          pytest SRT -x -v
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "pip install -r requirements/docs.txt"
          docs-folder: "docs/"
